services:
  postgres:
    image: postgis/postgis:18-3.6
    container_name: postgres

    restart: unless-stopped

    ports:
      - "127.0.0.1:5432:5432"

    env_file:
      - .env

    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
      NORMAL_USER: ${USER:-developer}
      NORMAL_USER_PASSWORD: ${NORMAL_USER_PASSWORD}

    volumes:
      # The data dir has changed from Posgres v18 onwards (it is now versioned)
      # Change ./data to your preferred Postgres data dir on the host
      - ./data:/var/lib/postgresql
      - ./initdb:/docker-entrypoint-initdb.d:ro
      - ./gis_data:/usr/local/gis_data
      # Uncomment if you later decide to provide custom config files.
      # - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro
      # - ./pg_hba.conf:/etc/postgresql/pg_hba.conf:ro

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d postgres"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

    stop_grace_period: 60s

    shm_size: 1gb

    networks:
      - postgres

  osm2pgsql:
    image: iboates/osm2pgsql:2.3.1

    environment:
      PGHOST: postgres
      PGDATABASE: osm_import
      PGUSER: ${NORMAL_USER}
      PGPASSWORD: ${NORMAL_USER_PASSWORD}

    volumes:
      - ./gis_data:/gis_data
      - ./flex:/flex:ro

    networks:
      - postgres

    depends_on:
      postgres:
        condition: service_healthy
    
  pgadmin:
    image: dpage/pgadmin4:9.17

    ports:
      - "localhost:5050:80"

    environment:
      

    networks: 
      - postgres

    depends-on:
      postgres:
        condition: service_healthy

networks:
  postgres:
    driver: bridge
